<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Chapter 4: Test of Independence of Variables – Statistics for Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter05_data_sampling.html" rel="next">
<link href="./chapter03_hypothesis_testing.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-81de787dd4773dbc0001c2dc1cc3016d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter04_test_of_independence.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 4: Test of Independence of Variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics for Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="./Statistics-for-Data-Science.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter01_descriptive_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 1: Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter02_data_distribution_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chapter 2: Data Distribution and Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter03_hypothesis_testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 3: Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter04_test_of_independence.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 4: Test of Independence of Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter05_data_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 5: Data Sampling Techniques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter06_data_preprocessing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chapter 6: Data Preprocessing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter07_dimension_reduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chapter 7: Data Dimension Reduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter08_data_clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 8: Data Clustering</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter09_data_classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 9: Data Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter10_regression_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 10: Regression Analysis</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#chapter-overview" id="toc-chapter-overview" class="nav-link active" data-scroll-target="#chapter-overview"><span class="header-section-number">6</span> Chapter Overview</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">6.1</span> Introduction</a></li>
  </ul></li>
  <li><a href="#the-concept-of-independence" id="toc-the-concept-of-independence" class="nav-link" data-scroll-target="#the-concept-of-independence"><span class="header-section-number">7</span> The Concept of Independence</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1"><span class="header-section-number">7.1</span> Introduction</a></li>
  <li><a href="#theory" id="toc-theory" class="nav-link" data-scroll-target="#theory"><span class="header-section-number">7.2</span> Theory</a>
  <ul class="collapse">
  <li><a href="#independence-for-categorical-variables" id="toc-independence-for-categorical-variables" class="nav-link" data-scroll-target="#independence-for-categorical-variables"><span class="header-section-number">7.2.1</span> Independence for Categorical Variables</a></li>
  <li><a href="#independence-for-continuous-variables" id="toc-independence-for-continuous-variables" class="nav-link" data-scroll-target="#independence-for-continuous-variables"><span class="header-section-number">7.2.2</span> Independence for Continuous Variables</a></li>
  <li><a href="#a-taxonomy-of-association-measures" id="toc-a-taxonomy-of-association-measures" class="nav-link" data-scroll-target="#a-taxonomy-of-association-measures"><span class="header-section-number">7.2.3</span> A Taxonomy of Association Measures</a></li>
  </ul></li>
  <li><a href="#example-identifying-the-correct-test" id="toc-example-identifying-the-correct-test" class="nav-link" data-scroll-target="#example-identifying-the-correct-test"><span class="header-section-number">7.3</span> Example: Identifying the Correct Test</a></li>
  <li><a href="#r-example-exploring-variable-relationships" id="toc-r-example-exploring-variable-relationships" class="nav-link" data-scroll-target="#r-example-exploring-variable-relationships"><span class="header-section-number">7.4</span> R Example: Exploring Variable Relationships</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">7.5</span> Exercises</a></li>
  </ul></li>
  <li><a href="#chi-square-test-of-independence" id="toc-chi-square-test-of-independence" class="nav-link" data-scroll-target="#chi-square-test-of-independence"><span class="header-section-number">8</span> Chi-Square Test of Independence</a>
  <ul class="collapse">
  <li><a href="#introduction-2" id="toc-introduction-2" class="nav-link" data-scroll-target="#introduction-2"><span class="header-section-number">8.1</span> Introduction</a></li>
  <li><a href="#theory-1" id="toc-theory-1" class="nav-link" data-scroll-target="#theory-1"><span class="header-section-number">8.2</span> Theory</a>
  <ul class="collapse">
  <li><a href="#the-test-statistic" id="toc-the-test-statistic" class="nav-link" data-scroll-target="#the-test-statistic"><span class="header-section-number">8.2.1</span> The Test Statistic</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">8.2.2</span> Assumptions</a></li>
  <li><a href="#yates-continuity-correction" id="toc-yates-continuity-correction" class="nav-link" data-scroll-target="#yates-continuity-correction"><span class="header-section-number">8.2.3</span> Yates’ Continuity Correction</a></li>
  <li><a href="#standardized-residuals" id="toc-standardized-residuals" class="nav-link" data-scroll-target="#standardized-residuals"><span class="header-section-number">8.2.4</span> Standardized Residuals</a></li>
  </ul></li>
  <li><a href="#example-chi-square-test" id="toc-example-chi-square-test" class="nav-link" data-scroll-target="#example-chi-square-test"><span class="header-section-number">8.3</span> Example: Chi-Square Test</a></li>
  <li><a href="#r-example-chi-square-test-of-independence" id="toc-r-example-chi-square-test-of-independence" class="nav-link" data-scroll-target="#r-example-chi-square-test-of-independence"><span class="header-section-number">8.4</span> R Example: Chi-Square Test of Independence</a></li>
  <li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1"><span class="header-section-number">8.5</span> Exercises</a></li>
  </ul></li>
  <li><a href="#fishers-exact-test" id="toc-fishers-exact-test" class="nav-link" data-scroll-target="#fishers-exact-test"><span class="header-section-number">9</span> Fisher’s Exact Test</a>
  <ul class="collapse">
  <li><a href="#introduction-3" id="toc-introduction-3" class="nav-link" data-scroll-target="#introduction-3"><span class="header-section-number">9.1</span> Introduction</a></li>
  <li><a href="#theory-2" id="toc-theory-2" class="nav-link" data-scroll-target="#theory-2"><span class="header-section-number">9.2</span> Theory</a>
  <ul class="collapse">
  <li><a href="#the-hypergeometric-distribution" id="toc-the-hypergeometric-distribution" class="nav-link" data-scroll-target="#the-hypergeometric-distribution"><span class="header-section-number">9.2.1</span> The Hypergeometric Distribution</a></li>
  <li><a href="#two-sided-fishers-test" id="toc-two-sided-fishers-test" class="nav-link" data-scroll-target="#two-sided-fishers-test"><span class="header-section-number">9.2.2</span> Two-Sided Fisher’s Test</a></li>
  <li><a href="#when-to-use-fishers-exact-test" id="toc-when-to-use-fishers-exact-test" class="nav-link" data-scroll-target="#when-to-use-fishers-exact-test"><span class="header-section-number">9.2.3</span> When to Use Fisher’s Exact Test</a></li>
  </ul></li>
  <li><a href="#example-fishers-exact-test" id="toc-example-fishers-exact-test" class="nav-link" data-scroll-target="#example-fishers-exact-test"><span class="header-section-number">9.3</span> Example: Fisher’s Exact Test</a></li>
  <li><a href="#r-example-fishers-exact-test" id="toc-r-example-fishers-exact-test" class="nav-link" data-scroll-target="#r-example-fishers-exact-test"><span class="header-section-number">9.4</span> R Example: Fisher’s Exact Test</a></li>
  <li><a href="#exercises-2" id="toc-exercises-2" class="nav-link" data-scroll-target="#exercises-2"><span class="header-section-number">9.5</span> Exercises</a></li>
  </ul></li>
  <li><a href="#cramérs-v-and-effect-size-for-categorical-association" id="toc-cramérs-v-and-effect-size-for-categorical-association" class="nav-link" data-scroll-target="#cramérs-v-and-effect-size-for-categorical-association"><span class="header-section-number">10</span> Cramér’s V and Effect Size for Categorical Association</a>
  <ul class="collapse">
  <li><a href="#introduction-4" id="toc-introduction-4" class="nav-link" data-scroll-target="#introduction-4"><span class="header-section-number">10.1</span> Introduction</a></li>
  <li><a href="#theory-3" id="toc-theory-3" class="nav-link" data-scroll-target="#theory-3"><span class="header-section-number">10.2</span> Theory</a>
  <ul class="collapse">
  <li><a href="#cramérs-v" id="toc-cramérs-v" class="nav-link" data-scroll-target="#cramérs-v"><span class="header-section-number">10.2.1</span> Cramér’s V</a></li>
  <li><a href="#the-phi-coefficient" id="toc-the-phi-coefficient" class="nav-link" data-scroll-target="#the-phi-coefficient"><span class="header-section-number">10.2.2</span> The Phi Coefficient</a></li>
  <li><a href="#goodman-and-kruskals-lambda" id="toc-goodman-and-kruskals-lambda" class="nav-link" data-scroll-target="#goodman-and-kruskals-lambda"><span class="header-section-number">10.2.3</span> Goodman and Kruskal’s Lambda</a></li>
  </ul></li>
  <li><a href="#example-cramérs-v" id="toc-example-cramérs-v" class="nav-link" data-scroll-target="#example-cramérs-v"><span class="header-section-number">10.3</span> Example: Cramér’s V</a></li>
  <li><a href="#r-example-cramérs-v-and-association-measures" id="toc-r-example-cramérs-v-and-association-measures" class="nav-link" data-scroll-target="#r-example-cramérs-v-and-association-measures"><span class="header-section-number">10.4</span> R Example: Cramér’s V and Association Measures</a></li>
  <li><a href="#exercises-3" id="toc-exercises-3" class="nav-link" data-scroll-target="#exercises-3"><span class="header-section-number">10.5</span> Exercises</a></li>
  </ul></li>
  <li><a href="#correlation-tests" id="toc-correlation-tests" class="nav-link" data-scroll-target="#correlation-tests"><span class="header-section-number">11</span> Correlation Tests</a>
  <ul class="collapse">
  <li><a href="#introduction-5" id="toc-introduction-5" class="nav-link" data-scroll-target="#introduction-5"><span class="header-section-number">11.1</span> Introduction</a></li>
  <li><a href="#theory-4" id="toc-theory-4" class="nav-link" data-scroll-target="#theory-4"><span class="header-section-number">11.2</span> Theory</a>
  <ul class="collapse">
  <li><a href="#pearson-correlation-test" id="toc-pearson-correlation-test" class="nav-link" data-scroll-target="#pearson-correlation-test"><span class="header-section-number">11.2.1</span> Pearson Correlation Test</a></li>
  <li><a href="#spearman-rank-correlation-test" id="toc-spearman-rank-correlation-test" class="nav-link" data-scroll-target="#spearman-rank-correlation-test"><span class="header-section-number">11.2.2</span> Spearman Rank Correlation Test</a></li>
  <li><a href="#interpreting-correlation" id="toc-interpreting-correlation" class="nav-link" data-scroll-target="#interpreting-correlation"><span class="header-section-number">11.2.3</span> Interpreting Correlation</a></li>
  </ul></li>
  <li><a href="#example-pearson-and-spearman-correlation-tests" id="toc-example-pearson-and-spearman-correlation-tests" class="nav-link" data-scroll-target="#example-pearson-and-spearman-correlation-tests"><span class="header-section-number">11.3</span> Example: Pearson and Spearman Correlation Tests</a></li>
  <li><a href="#r-example-pearson-and-spearman-correlation-tests" id="toc-r-example-pearson-and-spearman-correlation-tests" class="nav-link" data-scroll-target="#r-example-pearson-and-spearman-correlation-tests"><span class="header-section-number">11.4</span> R Example: Pearson and Spearman Correlation Tests</a></li>
  <li><a href="#exercises-4" id="toc-exercises-4" class="nav-link" data-scroll-target="#exercises-4"><span class="header-section-number">11.5</span> Exercises</a></li>
  </ul></li>
  <li><a href="#point-biserial-and-phi-coefficients" id="toc-point-biserial-and-phi-coefficients" class="nav-link" data-scroll-target="#point-biserial-and-phi-coefficients"><span class="header-section-number">12</span> Point-Biserial and Phi Coefficients</a>
  <ul class="collapse">
  <li><a href="#introduction-6" id="toc-introduction-6" class="nav-link" data-scroll-target="#introduction-6"><span class="header-section-number">12.1</span> Introduction</a></li>
  <li><a href="#theory-5" id="toc-theory-5" class="nav-link" data-scroll-target="#theory-5"><span class="header-section-number">12.2</span> Theory</a>
  <ul class="collapse">
  <li><a href="#point-biserial-correlation-r_pb" id="toc-point-biserial-correlation-r_pb" class="nav-link" data-scroll-target="#point-biserial-correlation-r_pb"><span class="header-section-number">12.2.1</span> Point-Biserial Correlation (<span class="math inline">\(r_{pb}\)</span>)</a></li>
  <li><a href="#phi-coefficient-phi" id="toc-phi-coefficient-phi" class="nav-link" data-scroll-target="#phi-coefficient-phi"><span class="header-section-number">12.2.2</span> Phi Coefficient (<span class="math inline">\(\phi\)</span>)</a></li>
  <li><a href="#biserial-vs.-point-biserial" id="toc-biserial-vs.-point-biserial" class="nav-link" data-scroll-target="#biserial-vs.-point-biserial"><span class="header-section-number">12.2.3</span> Biserial vs.&nbsp;Point-Biserial</a></li>
  </ul></li>
  <li><a href="#example-point-biserial-correlation" id="toc-example-point-biserial-correlation" class="nav-link" data-scroll-target="#example-point-biserial-correlation"><span class="header-section-number">12.3</span> Example: Point-Biserial Correlation</a></li>
  <li><a href="#r-example-point-biserial-and-phi-coefficients" id="toc-r-example-point-biserial-and-phi-coefficients" class="nav-link" data-scroll-target="#r-example-point-biserial-and-phi-coefficients"><span class="header-section-number">12.4</span> R Example: Point-Biserial and Phi Coefficients</a></li>
  <li><a href="#exercises-5" id="toc-exercises-5" class="nav-link" data-scroll-target="#exercises-5"><span class="header-section-number">12.5</span> Exercises</a></li>
  </ul></li>
  <li><a href="#partial-correlation" id="toc-partial-correlation" class="nav-link" data-scroll-target="#partial-correlation"><span class="header-section-number">13</span> Partial Correlation</a>
  <ul class="collapse">
  <li><a href="#introduction-7" id="toc-introduction-7" class="nav-link" data-scroll-target="#introduction-7"><span class="header-section-number">13.1</span> Introduction</a></li>
  <li><a href="#theory-6" id="toc-theory-6" class="nav-link" data-scroll-target="#theory-6"><span class="header-section-number">13.2</span> Theory</a>
  <ul class="collapse">
  <li><a href="#first-order-partial-correlation" id="toc-first-order-partial-correlation" class="nav-link" data-scroll-target="#first-order-partial-correlation"><span class="header-section-number">13.2.1</span> First-Order Partial Correlation</a></li>
  <li><a href="#significance-testing" id="toc-significance-testing" class="nav-link" data-scroll-target="#significance-testing"><span class="header-section-number">13.2.2</span> Significance Testing</a></li>
  <li><a href="#partial-vs.-semi-partial-correlation" id="toc-partial-vs.-semi-partial-correlation" class="nav-link" data-scroll-target="#partial-vs.-semi-partial-correlation"><span class="header-section-number">13.2.3</span> Partial vs.&nbsp;Semi-Partial Correlation</a></li>
  <li><a href="#spurious-correlation" id="toc-spurious-correlation" class="nav-link" data-scroll-target="#spurious-correlation"><span class="header-section-number">13.2.4</span> Spurious Correlation</a></li>
  </ul></li>
  <li><a href="#example-partial-correlation" id="toc-example-partial-correlation" class="nav-link" data-scroll-target="#example-partial-correlation"><span class="header-section-number">13.3</span> Example: Partial Correlation</a></li>
  <li><a href="#r-example-partial-correlation" id="toc-r-example-partial-correlation" class="nav-link" data-scroll-target="#r-example-partial-correlation"><span class="header-section-number">13.4</span> R Example: Partial Correlation</a></li>
  <li><a href="#exercises-6" id="toc-exercises-6" class="nav-link" data-scroll-target="#exercises-6"><span class="header-section-number">13.5</span> Exercises</a></li>
  </ul></li>
  <li><a href="#chapter-lab-activity-exploring-independence-with-the-titanic-and-mtcars-datasets" id="toc-chapter-lab-activity-exploring-independence-with-the-titanic-and-mtcars-datasets" class="nav-link" data-scroll-target="#chapter-lab-activity-exploring-independence-with-the-titanic-and-mtcars-datasets"><span class="header-section-number">14</span> Chapter Lab Activity: Exploring Independence with the <code>titanic</code> and <code>mtcars</code> Datasets</a>
  <ul class="collapse">
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives"><span class="header-section-number">14.1</span> Objectives</a></li>
  <li><a href="#the-datasets" id="toc-the-datasets" class="nav-link" data-scroll-target="#the-datasets"><span class="header-section-number">14.2</span> The Datasets</a></li>
  <li><a href="#lab-task-1-survival-class-chi-square-test" id="toc-lab-task-1-survival-class-chi-square-test" class="nav-link" data-scroll-target="#lab-task-1-survival-class-chi-square-test"><span class="header-section-number">14.3</span> Lab Task 1: Survival × Class — Chi-Square Test</a></li>
  <li><a href="#lab-task-2-survival-sex-fishers-exact-test" id="toc-lab-task-2-survival-sex-fishers-exact-test" class="nav-link" data-scroll-target="#lab-task-2-survival-sex-fishers-exact-test"><span class="header-section-number">14.4</span> Lab Task 2: Survival × Sex — Fisher’s Exact Test</a></li>
  <li><a href="#lab-task-3-correlation-analysis-mtcars" id="toc-lab-task-3-correlation-analysis-mtcars" class="nav-link" data-scroll-target="#lab-task-3-correlation-analysis-mtcars"><span class="header-section-number">14.5</span> Lab Task 3: Correlation Analysis — mtcars</a></li>
  <li><a href="#lab-task-4-partial-correlation-controlling-for-weight" id="toc-lab-task-4-partial-correlation-controlling-for-weight" class="nav-link" data-scroll-target="#lab-task-4-partial-correlation-controlling-for-weight"><span class="header-section-number">14.6</span> Lab Task 4: Partial Correlation — Controlling for Weight</a></li>
  <li><a href="#lab-task-5-comprehensive-visualization" id="toc-lab-task-5-comprehensive-visualization" class="nav-link" data-scroll-target="#lab-task-5-comprehensive-visualization"><span class="header-section-number">14.7</span> Lab Task 5: Comprehensive Visualization</a></li>
  <li><a href="#lab-discussion-questions" id="toc-lab-discussion-questions" class="nav-link" data-scroll-target="#lab-discussion-questions"><span class="header-section-number">14.8</span> Lab Discussion Questions</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">15</span> Chapter Summary</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">15.1</span> Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">15.2</span> References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 4: Test of Independence of Variables</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<hr>
<section id="chapter-overview" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Chapter Overview</h1>
<section id="introduction" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">6.1</span> Introduction</h2>
<p>One of the most fundamental questions in data analysis is whether two variables are <strong>related</strong> to each other, or whether they vary <strong>independently</strong>. Does a patient’s smoking status relate to their disease outcome? Is a student’s program of study associated with their level of satisfaction? Do income and education move together? Tests of independence answer these questions formally, across all combinations of variable types.</p>
<p>This chapter covers:</p>
<ul>
<li><strong>The Concept of Independence</strong> — theoretical foundations linking back to probability</li>
<li><strong>Chi-Square Test of Independence</strong> — testing association between two categorical variables</li>
<li><strong>Fisher’s Exact Test</strong> — a robust alternative for small or sparse contingency tables</li>
<li><strong>Cramér’s V and Effect Size</strong> — quantifying the strength of categorical association</li>
<li><strong>Correlation Tests</strong> — Pearson and Spearman for continuous and ordinal variables</li>
<li><strong>Point-Biserial and Phi Coefficients</strong> — association involving binary variables</li>
<li><strong>Partial Correlation</strong> — measuring association while controlling for a third variable</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<p>By the end of this chapter, you will be able to:</p>
<ol type="1">
<li>Distinguish statistical independence from dependence for different variable types.</li>
<li>Conduct and interpret chi-square and Fisher’s exact tests for categorical data.</li>
<li>Compute and interpret Cramér’s V as a measure of association strength.</li>
<li>Test the significance of Pearson and Spearman correlations.</li>
<li>Select the appropriate association measure based on variable types.</li>
<li>Compute partial correlations to control for confounding variables.</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
<section id="the-concept-of-independence" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> The Concept of Independence</h1>
<section id="introduction-1" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="introduction-1"><span class="header-section-number">7.1</span> Introduction</h2>
<p>In Chapter 2, we defined statistical independence in probability terms: two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if <span class="math inline">\(P(A \cap B) = P(A) \cdot P(B)\)</span>. In data analysis, we extend this idea to variables: two variables are <strong>statistically independent</strong> if knowing the value of one provides no information about the value of the other. When they are not independent, we say they are <strong>associated</strong> or <strong>dependent</strong>.</p>
<p>Testing for independence is not the same as proving causation. Association tells us that two variables move together — it says nothing about which causes which, or whether both are driven by a third variable. This distinction is critical in data science, where spurious correlations are common in large datasets.</p>
</section>
<section id="theory" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="theory"><span class="header-section-number">7.2</span> Theory</h2>
<section id="independence-for-categorical-variables" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="independence-for-categorical-variables"><span class="header-section-number">7.2.1</span> Independence for Categorical Variables</h3>
<p>Two categorical variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent if, for all categories <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>:</p>
<p><span class="math display">\[P(X = i \cap Y = j) = P(X = i) \cdot P(Y = j)\]</span></p>
<p>In a contingency table, this means every <strong>observed cell frequency</strong> should equal the corresponding <strong>expected cell frequency</strong> under independence:</p>
<p><span class="math display">\[E_{ij} = \frac{(\text{Row } i \text{ total}) \times (\text{Column } j \text{ total})}{\text{Grand total}} = \frac{R_i \cdot C_j}{N}\]</span></p>
<p>Any systematic departure of observed frequencies from expected frequencies is evidence of association.</p>
</section>
<section id="independence-for-continuous-variables" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="independence-for-continuous-variables"><span class="header-section-number">7.2.2</span> Independence for Continuous Variables</h3>
<p>Two continuous variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent if their <strong>joint distribution</strong> equals the product of their marginal distributions:</p>
<p><span class="math display">\[f(x, y) = f_X(x) \cdot f_Y(y)\]</span></p>
<p>In practice, we test a weaker condition: <strong>linear independence</strong> (zero correlation). Note that zero correlation does not guarantee full independence — two variables can be nonlinearly related yet have zero Pearson correlation. This is why visualization always accompanies formal tests.</p>
</section>
<section id="a-taxonomy-of-association-measures" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="a-taxonomy-of-association-measures"><span class="header-section-number">7.2.3</span> A Taxonomy of Association Measures</h3>
<p>The correct test and measure of association depend on the <strong>types of variables</strong> being compared:</p>
<table class="table-striped caption-top table">
<caption>Association measures by variable type</caption>
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 15%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Variable 1</th>
<th>Variable 2</th>
<th>Test</th>
<th>Effect Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Categorical</td>
<td>Categorical</td>
<td>Chi-square / Fisher’s</td>
<td>Cramér’s V</td>
</tr>
<tr class="even">
<td>Continuous</td>
<td>Continuous</td>
<td>Pearson / Spearman correlation test</td>
<td><span class="math inline">\(r\)</span> / <span class="math inline">\(\rho\)</span></td>
</tr>
<tr class="odd">
<td>Binary</td>
<td>Continuous</td>
<td>Point-biserial correlation test</td>
<td><span class="math inline">\(r_{pb}\)</span></td>
</tr>
<tr class="even">
<td>Binary</td>
<td>Binary</td>
<td>Chi-square / Fisher’s</td>
<td>Phi (<span class="math inline">\(\phi\)</span>)</td>
</tr>
<tr class="odd">
<td>Continuous (controlling for <span class="math inline">\(Z\)</span>)</td>
<td>Continuous</td>
<td>Partial correlation</td>
<td>Partial <span class="math inline">\(r\)</span></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="example-identifying-the-correct-test" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="example-identifying-the-correct-test"><span class="header-section-number">7.3</span> Example: Identifying the Correct Test</h2>
<p><strong>Example 4.1.</strong> A researcher collects data on university students. Identify the appropriate test for each pair of variables:</p>
<table class="table-striped caption-top table">
<caption>Example 4.1 — Test selection by variable type</caption>
<colgroup>
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Variable 1</th>
<th>Variable 2</th>
<th>Appropriate Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Faculty (Science, Arts, Business)</td>
<td>Pass/Fail status</td>
<td>Chi-square test</td>
</tr>
<tr class="even">
<td>Age (years)</td>
<td>GPA (0–4 scale)</td>
<td>Pearson or Spearman correlation</td>
</tr>
<tr class="odd">
<td>Gender (Male/Female)</td>
<td>Exam score (continuous)</td>
<td>Point-biserial correlation</td>
</tr>
<tr class="even">
<td>Smoking (Yes/No)</td>
<td>Disease (Yes/No)</td>
<td>Chi-square or Fisher’s exact</td>
</tr>
<tr class="odd">
<td>Income</td>
<td>Happiness (controlling for age)</td>
<td>Partial correlation</td>
</tr>
</tbody>
</table>
</section>
<section id="r-example-exploring-variable-relationships" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="r-example-exploring-variable-relationships"><span class="header-section-number">7.4</span> R Example: Exploring Variable Relationships</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>=== Variable Type Overview ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Categorical × Categorical: transmission vs. efficiency</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Continuous × Continuous:   mpg vs. hp</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Binary × Continuous:       transmission vs. mpg</code></pre>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Contingency Table: Transmission × Fuel Efficiency</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">High</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Automatic</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manual</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sum</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">32</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter04_test_of_independence_files/figure-html/independence-viz-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Code explanation:</strong></p>
<ul>
<li><code>addmargins(table())</code> adds row and column totals to the contingency table — essential for computing expected frequencies by hand.</li>
<li><code>geom_bar(position = "fill")</code> creates proportional stacked bars, making differences in conditional distributions visually obvious.</li>
<li>Visual inspection always precedes formal testing — if proportions look identical across groups, a significant test result warrants careful scrutiny.</li>
</ul>
</section>
<section id="exercises" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="exercises"><span class="header-section-number">7.5</span> Exercises</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise 4.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>For each of the following research questions, identify: (a) the variable types, (b) the appropriate test of independence, and (c) what a significant result would mean substantively.</p>
<ol type="1">
<li>Do male and female students differ in their choice of academic major?</li>
<li>Is there a relationship between study hours per week and final exam score?</li>
<li>Does coffee consumption (cups/day) relate to reported anxiety level (1–10 scale)?</li>
<li>Is being a first-generation student associated with dropout status (yes/no)?</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
<section id="chi-square-test-of-independence" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Chi-Square Test of Independence</h1>
<section id="introduction-2" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="introduction-2"><span class="header-section-number">8.1</span> Introduction</h2>
<p>The <strong>chi-square test of independence</strong> is the standard procedure for testing whether two categorical variables are associated. It compares the <strong>observed</strong> frequencies in a contingency table to the <strong>expected</strong> frequencies that would arise if the variables were truly independent. It is among the most widely used tests in social science, medical research, and data science — applicable whenever we want to know if two categorical groupings are related.</p>
</section>
<section id="theory-1" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="theory-1"><span class="header-section-number">8.2</span> Theory</h2>
<section id="the-test-statistic" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="the-test-statistic"><span class="header-section-number">8.2.1</span> The Test Statistic</h3>
<p>Given a contingency table with <span class="math inline">\(r\)</span> rows and <span class="math inline">\(c\)</span> columns, the chi-square test statistic is:</p>
<p><span class="math display">\[\chi^2 = \sum_{i=1}^{r} \sum_{j=1}^{c} \frac{(O_{ij} - E_{ij})^2}{E_{ij}}\]</span></p>
<p>where <span class="math inline">\(O_{ij}\)</span> is the observed frequency and <span class="math inline">\(E_{ij} = R_i C_j / N\)</span> is the expected frequency in cell <span class="math inline">\((i,j)\)</span>.</p>
<p>Under <span class="math inline">\(H_0\)</span> (independence), <span class="math inline">\(\chi^2 \sim \chi^2((r-1)(c-1))\)</span> approximately.</p>
<p><strong>Hypotheses:</strong> <span class="math display">\[H_0: \text{The two variables are independent}\]</span> <span class="math display">\[H_1: \text{The two variables are associated}\]</span></p>
</section>
<section id="assumptions" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="assumptions"><span class="header-section-number">8.2.2</span> Assumptions</h3>
<ol type="1">
<li>Observations are <strong>independent</strong> (each subject appears in exactly one cell).</li>
<li>The data are <strong>counts</strong> (not percentages or proportions).</li>
<li><strong>Expected cell frequencies</strong> are sufficiently large:
<ul>
<li>At least 80% of cells have <span class="math inline">\(E_{ij} \geq 5\)</span></li>
<li>No cell has <span class="math inline">\(E_{ij} &lt; 1\)</span></li>
</ul></li>
</ol>
<p>When these conditions are violated — typically with small samples or rare categories — use <strong>Fisher’s Exact Test</strong> (Section 3).</p>
</section>
<section id="yates-continuity-correction" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="yates-continuity-correction"><span class="header-section-number">8.2.3</span> Yates’ Continuity Correction</h3>
<p>For 2×2 tables, a continuity correction is sometimes applied to account for the fact that we are approximating a discrete distribution with a continuous one:</p>
<p><span class="math display">\[\chi^2_{\text{Yates}} = \sum \frac{(|O_{ij} - E_{ij}| - 0.5)^2}{E_{ij}}\]</span></p>
<p>Yates’ correction is conservative (reduces test power) and is debated in the literature. Many statisticians prefer Fisher’s Exact Test for 2×2 tables regardless of sample size.</p>
</section>
<section id="standardized-residuals" class="level3" data-number="8.2.4">
<h3 data-number="8.2.4" class="anchored" data-anchor-id="standardized-residuals"><span class="header-section-number">8.2.4</span> Standardized Residuals</h3>
<p>A significant chi-square test tells us <em>that</em> association exists but not <em>where</em> it comes from. <strong>Standardized residuals</strong> identify which cells contribute most:</p>
<p><span class="math display">\[r_{ij} = \frac{O_{ij} - E_{ij}}{\sqrt{E_{ij}}}\]</span></p>
<p>Cells with <span class="math inline">\(|r_{ij}| &gt; 2\)</span> are typically considered notably discrepant from independence.</p>
</section>
</section>
<section id="example-chi-square-test" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="example-chi-square-test"><span class="header-section-number">8.3</span> Example: Chi-Square Test</h2>
<p><strong>Example 4.2.</strong> A researcher investigates whether exercise frequency is associated with self-reported health status among 200 adults.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Poor Health</th>
<th>Good Health</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rarely exercises</td>
<td>40</td>
<td>25</td>
<td>65</td>
</tr>
<tr class="even">
<td>Sometimes exercises</td>
<td>30</td>
<td>45</td>
<td>75</td>
</tr>
<tr class="odd">
<td>Regularly exercises</td>
<td>15</td>
<td>45</td>
<td>60</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong>85</strong></td>
<td><strong>115</strong></td>
<td><strong>200</strong></td>
</tr>
</tbody>
</table>
<p><strong>Expected frequencies under <span class="math inline">\(H_0\)</span>:</strong> <span class="math display">\[E_{11} = \frac{65 \times 85}{200} = 27.6, \quad E_{12} = \frac{65 \times 115}{200} = 37.4\]</span> <span class="math display">\[E_{21} = \frac{75 \times 85}{200} = 31.9, \quad E_{22} = \frac{75 \times 115}{200} = 43.1\]</span> <span class="math display">\[E_{31} = \frac{60 \times 85}{200} = 25.5, \quad E_{32} = \frac{60 \times 115}{200} = 34.5\]</span></p>
<p><strong>Test statistic:</strong> <span class="math display">\[\chi^2 = \frac{(40-27.6)^2}{27.6} + \frac{(25-37.4)^2}{37.4} + \cdots = 5.58 + 4.12 + 0.11 + 0.08 + 4.33 + 3.20 = 17.42\]</span></p>
<p><strong>df</strong> <span class="math inline">\(= (3-1)(2-1) = 2\)</span>, <strong>p-value</strong> <span class="math inline">\(= P(\chi^2_2 &gt; 17.42) &lt; 0.001\)</span></p>
<p><strong>Decision:</strong> Reject <span class="math inline">\(H_0\)</span> — exercise frequency and health status are significantly associated (<span class="math inline">\(\chi^2(2) = 17.42\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</p>
<p><strong>Standardized residuals</strong> reveal the pattern: “Rarely exercises / Poor Health” is notably higher than expected (<span class="math inline">\(r = +2.36\)</span>), while “Regularly exercises / Poor Health” is notably lower (<span class="math inline">\(r = -2.08\)</span>) — people who exercise regularly are less likely to report poor health.</p>
</section>
<section id="r-example-chi-square-test-of-independence" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="r-example-chi-square-test-of-independence"><span class="header-section-number">8.4</span> R Example: Chi-Square Test of Independence</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Observed Frequencies: Exercise × Health Status</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Poor</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Good</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rarely</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">65</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sometimes</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Regularly</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">60</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sum</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">115</td>
<td style="text-align: right;">200</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  exercise_health
X-squared = 17.352, df = 2, p-value = 0.0001706</code></pre>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Expected Frequencies Under H₀ (Independence)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Poor</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Good</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rarely</td>
<td style="text-align: right;">27.62</td>
<td style="text-align: right;">37.38</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sometimes</td>
<td style="text-align: right;">31.88</td>
<td style="text-align: right;">43.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Regularly</td>
<td style="text-align: right;">25.50</td>
<td style="text-align: right;">34.50</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Standardized Residuals (|r| &gt; 2 = notable departure)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Poor</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Good</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rarely</td>
<td style="text-align: right; color: tomato !important;">3.779</td>
<td style="text-align: right; color: tomato !important;">-3.779</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sometimes</td>
<td style="text-align: right; color: black !important;">-0.554</td>
<td style="text-align: right; color: black !important;">0.554</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Regularly</td>
<td style="text-align: right; color: tomato !important;">-3.277</td>
<td style="text-align: right; color: tomato !important;">3.277</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter04_test_of_independence_files/figure-html/chisq-plot-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Code explanation:</strong></p>
<ul>
<li><code>chisq.test(table, correct = FALSE)</code> runs the chi-square test without Yates’ correction. Set <code>correct = TRUE</code> for Yates’ correction on 2×2 tables.</li>
<li>The result object stores <code>$expected</code> (expected frequencies), <code>$stdres</code> (standardized residuals), and <code>$p.value</code>.</li>
<li>The dashed horizontal line marks the overall “poor health” rate — bars above it indicate excess poor health relative to the population average, making deviations from independence visually clear.</li>
</ul>
<p><strong>Try modifying:</strong> Check <code>all(chi_result$expected &gt;= 5)</code> to verify the minimum expected frequency assumption is met.</p>
</section>
<section id="exercises-1" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="exercises-1"><span class="header-section-number">8.5</span> Exercises</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise 4.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use the <code>HairEyeColor</code> dataset built into R (hair color × eye color × sex for 592 statistics students).</p>
<ol type="a">
<li>Collapse across sex: <code>margin.table(HairEyeColor, c(1,2))</code> to get a Hair × Eye contingency table.</li>
<li>Run a chi-square test. Are hair and eye color independent?</li>
<li>Compute and display standardized residuals. Which hair-eye combinations are most over- or under-represented?</li>
<li>Produce a proportional stacked bar chart and interpret the pattern.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise 4.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>A clinical study records treatment type (Drug A, Drug B, Placebo) and recovery outcome (Recovered, Not Recovered) for 150 patients.</p>
<ol type="a">
<li>Create the contingency table in R with <code>matrix()</code>.</li>
<li>Verify the minimum expected frequency assumption. If violated, what alternative test should you use?</li>
<li>Run the chi-square test and report results in APA format: <span class="math inline">\(\chi^2(df) = X.XX\)</span>, <span class="math inline">\(p = .XXX\)</span>.</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
<section id="fishers-exact-test" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Fisher’s Exact Test</h1>
<section id="introduction-3" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="introduction-3"><span class="header-section-number">9.1</span> Introduction</h2>
<p>The chi-square test relies on a large-sample approximation — when expected cell frequencies are small (below 5), the <span class="math inline">\(\chi^2\)</span> approximation becomes unreliable and p-values are inaccurate. <strong>Fisher’s Exact Test</strong> solves this problem by computing the <strong>exact</strong> probability of observing the table, or one more extreme, under <span class="math inline">\(H_0\)</span> of independence. It was originally designed for 2×2 tables but extends to larger tables. In data science and biomedical research, small samples and rare events are common — Fisher’s test is an essential tool.</p>
</section>
<section id="theory-2" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="theory-2"><span class="header-section-number">9.2</span> Theory</h2>
<section id="the-hypergeometric-distribution" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="the-hypergeometric-distribution"><span class="header-section-number">9.2.1</span> The Hypergeometric Distribution</h3>
<p>Fisher’s test is based on the <strong>hypergeometric distribution</strong> — the exact probability of a specific 2×2 table with fixed marginal totals <span class="math inline">\((R_1, R_2, C_1, C_2)\)</span>:</p>
<p><span class="math display">\[P\left(\begin{bmatrix} a &amp; b \\ c &amp; d \end{bmatrix}\right) = \frac{\binom{R_1}{a}\binom{R_2}{c}}{\binom{N}{C_1}} = \frac{(R_1)!(R_2)!(C_1)!(C_2)!}{N! \cdot a! \cdot b! \cdot c! \cdot d!}\]</span></p>
<p>The p-value is the sum of probabilities for all tables as extreme as, or more extreme than, the observed table — while keeping marginal totals fixed.</p>
</section>
<section id="two-sided-fishers-test" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="two-sided-fishers-test"><span class="header-section-number">9.2.2</span> Two-Sided Fisher’s Test</h3>
<p>For two-sided tests, “more extreme” is defined as tables with probability <strong>less than or equal to</strong> the probability of the observed table. R’s <code>fisher.test()</code> implements this by default.</p>
</section>
<section id="when-to-use-fishers-exact-test" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="when-to-use-fishers-exact-test"><span class="header-section-number">9.2.3</span> When to Use Fisher’s Exact Test</h3>
<table class="table-striped caption-top table">
<caption>Fisher’s Exact Test usage guidelines</caption>
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Situation</th>
<th>Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Any cell has <span class="math inline">\(E_{ij} &lt; 5\)</span></td>
<td>Use Fisher’s</td>
</tr>
<tr class="even">
<td>Total <span class="math inline">\(N &lt; 20\)</span></td>
<td>Use Fisher’s</td>
</tr>
<tr class="odd">
<td>2×2 table, any sample size</td>
<td>Fisher’s is always valid (some prefer it over chi-square)</td>
</tr>
<tr class="even">
<td>Large <span class="math inline">\(r \times c\)</span> table, large <span class="math inline">\(N\)</span></td>
<td>Chi-square is adequate</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="example-fishers-exact-test" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="example-fishers-exact-test"><span class="header-section-number">9.3</span> Example: Fisher’s Exact Test</h2>
<p><strong>Example 4.3.</strong> A rare disease study examines whether a genetic marker is associated with disease status. Only 14 subjects are available.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Disease</th>
<th>No Disease</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Marker Present</td>
<td>5</td>
<td>2</td>
<td>7</td>
</tr>
<tr class="even">
<td>Marker Absent</td>
<td>1</td>
<td>6</td>
<td>7</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>6</strong></td>
<td><strong>8</strong></td>
<td><strong>14</strong></td>
</tr>
</tbody>
</table>
<p><strong>Expected frequencies:</strong> <span class="math inline">\(E_{11} = 6 \times 7/14 = 3.0\)</span> — below 5, so chi-square is inappropriate.</p>
<p><strong>Fisher’s exact p-value (two-sided):</strong> <span class="math inline">\(p = 0.103\)</span></p>
<p><strong>Decision:</strong> Fail to reject <span class="math inline">\(H_0\)</span> at <span class="math inline">\(\alpha = 0.05\)</span>. Despite the apparent pattern, there is insufficient evidence to conclude the marker is associated with disease — likely due to the very small sample size.</p>
<p><strong>Interpretation note:</strong> This example illustrates an important limitation. The study is severely <strong>underpowered</strong> — a larger study might well find significance. Fisher’s test is honest about uncertainty; it does not manufacture significance from sparse data.</p>
</section>
<section id="r-example-fishers-exact-test" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="r-example-fishers-exact-test"><span class="header-section-number">9.4</span> R Example: Fisher’s Exact Test</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Observed: Genetic Marker × Disease Status</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Disease</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No Disease</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Present</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Absent</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sum</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">14</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Expected frequencies:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Disease
Marker    Disease No Disease
  Present       3          4
  Absent        3          4</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Minimum expected frequency: 3 — chi-square assumption violated!</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  marker_disease
p-value = 0.1026
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
   0.7203391 817.9820107
sample estimates:
odds ratio 
  11.71745 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Test Comparison: Small Sample Scenario</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Test</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Appropriate?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chi-Square (no correction)</td>
<td style="text-align: left;">4.667</td>
<td style="text-align: right;">0.0308</td>
<td style="text-align: left; font-weight: bold; color: tomato !important;">No (E &lt; 5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chi-Square (Yates' correction)</td>
<td style="text-align: left;">2.625</td>
<td style="text-align: right;">0.1052</td>
<td style="text-align: left; font-weight: bold; color: tomato !important;">No (E &lt; 5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fisher's Exact Test</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">0.1026</td>
<td style="text-align: left; font-weight: bold; color: darkgreen !important;">Yes ✓</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter04_test_of_independence_files/figure-html/fisher-plot-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Code explanation:</strong></p>
<ul>
<li><code>fisher.test(table, alternative)</code> computes the exact p-value. For 2×2 tables it also returns an <strong>odds ratio</strong> with a confidence interval — a useful effect measure.</li>
<li>The comparison table illustrates how chi-square p-values are unreliable with small expected frequencies — they differ substantially from Fisher’s exact result.</li>
<li>The balloon plot is an intuitive alternative to a contingency table for small tables: bubble area represents cell count, making the pattern immediately visible.</li>
</ul>
</section>
<section id="exercises-2" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="exercises-2"><span class="header-section-number">9.5</span> Exercises</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise 4.4
</div>
</div>
<div class="callout-body-container callout-body">
<p>A new teaching intervention is tested in two small classrooms. Results:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Passed</th>
<th>Failed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intervention</td>
<td>8</td>
<td>2</td>
</tr>
<tr class="even">
<td>Control</td>
<td>4</td>
<td>6</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Check whether chi-square assumptions are met.</li>
<li>Run Fisher’s Exact Test. What is the p-value and odds ratio?</li>
<li>Interpret the odds ratio in plain language.</li>
<li>What would a larger study need to show to confirm this result?</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
<section id="cramérs-v-and-effect-size-for-categorical-association" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Cramér’s V and Effect Size for Categorical Association</h1>
<section id="introduction-4" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="introduction-4"><span class="header-section-number">10.1</span> Introduction</h2>
<p>A significant chi-square test only tells us that an association <strong>exists</strong> — it does not say how <strong>strong</strong> it is. With large samples, even trivially weak associations become statistically significant. <strong>Effect size measures</strong> for categorical variables answer the practical question: <em>How strongly are these two variables related?</em> The most versatile measure is <strong>Cramér’s V</strong>, which standardizes chi-square to a 0–1 scale regardless of table dimensions.</p>
</section>
<section id="theory-3" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="theory-3"><span class="header-section-number">10.2</span> Theory</h2>
<section id="cramérs-v" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="cramérs-v"><span class="header-section-number">10.2.1</span> Cramér’s V</h3>
<p>Cramér’s V is derived from the chi-square statistic, normalized to fall between 0 and 1:</p>
<p><span class="math display">\[V = \sqrt{\frac{\chi^2 / N}{\min(r-1, c-1)}}\]</span></p>
<p>where <span class="math inline">\(N\)</span> is the total sample size, <span class="math inline">\(r\)</span> is the number of rows, and <span class="math inline">\(c\)</span> is the number of columns.</p>
<ul>
<li><span class="math inline">\(V = 0\)</span>: Perfect independence (no association)</li>
<li><span class="math inline">\(V = 1\)</span>: Perfect association</li>
</ul>
<p><strong>Interpretation benchmarks</strong> (Cohen, 1988), adjusted for table size:</p>
<table class="table-striped caption-top table">
<caption>Cramér’s V interpretation by table dimensions</caption>
<thead>
<tr class="header">
<th>Table Size</th>
<th>Small</th>
<th>Medium</th>
<th>Large</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2×2</td>
<td>0.10</td>
<td>0.30</td>
<td>0.50</td>
</tr>
<tr class="even">
<td>3×3</td>
<td>0.07</td>
<td>0.21</td>
<td>0.35</td>
</tr>
<tr class="odd">
<td>4×4</td>
<td>0.06</td>
<td>0.17</td>
<td>0.29</td>
</tr>
</tbody>
</table>
</section>
<section id="the-phi-coefficient" class="level3" data-number="10.2.2">
<h3 data-number="10.2.2" class="anchored" data-anchor-id="the-phi-coefficient"><span class="header-section-number">10.2.2</span> The Phi Coefficient</h3>
<p>For 2×2 tables specifically, the <strong>phi coefficient</strong> <span class="math inline">\(\phi\)</span> is a simpler equivalent:</p>
<p><span class="math display">\[\phi = \sqrt{\frac{\chi^2}{N}} = \frac{ad - bc}{\sqrt{(a+b)(c+d)(a+c)(b+d)}}\]</span></p>
<p><span class="math inline">\(\phi\)</span> ranges from <span class="math inline">\(-1\)</span> to <span class="math inline">\(+1\)</span> for 2×2 tables (with sign indicating direction) and equals Cramér’s V when <span class="math inline">\(\min(r-1, c-1) = 1\)</span>.</p>
</section>
<section id="goodman-and-kruskals-lambda" class="level3" data-number="10.2.3">
<h3 data-number="10.2.3" class="anchored" data-anchor-id="goodman-and-kruskals-lambda"><span class="header-section-number">10.2.3</span> Goodman and Kruskal’s Lambda</h3>
<p>An alternative measure of association is <strong>Lambda</strong> (<span class="math inline">\(\lambda\)</span>), which measures the <strong>proportional reduction in prediction error</strong> — how much better we can predict one variable knowing the other:</p>
<p><span class="math display">\[\lambda = \frac{\sum_j \max_i f_{ij} - \max_i R_i}{N - \max_i R_i}\]</span></p>
<p><span class="math inline">\(\lambda = 0\)</span> means knowing <span class="math inline">\(X\)</span> does not help predict <span class="math inline">\(Y\)</span>; <span class="math inline">\(\lambda = 1\)</span> means perfect prediction.</p>
</section>
</section>
<section id="example-cramérs-v" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="example-cramérs-v"><span class="header-section-number">10.3</span> Example: Cramér’s V</h2>
<p><strong>Example 4.4.</strong> Returning to the exercise × health study (Example 4.2): <span class="math inline">\(\chi^2 = 17.42\)</span>, <span class="math inline">\(N = 200\)</span>, table is 3×2.</p>
<p><span class="math display">\[V = \sqrt{\frac{17.42/200}{\min(3-1, 2-1)}} = \sqrt{\frac{0.0871}{1}} = \sqrt{0.0871} \approx 0.295\]</span></p>
<p>For a table with <span class="math inline">\(\min(r-1, c-1) = 1\)</span>, benchmarks are 0.10/0.30/0.50 (small/medium/large). <span class="math inline">\(V = 0.295\)</span> is close to a <strong>medium effect</strong> — the association between exercise and health is statistically significant and of moderate practical importance.</p>
</section>
<section id="r-example-cramérs-v-and-association-measures" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="r-example-cramérs-v-and-association-measures"><span class="header-section-number">10.4</span> R Example: Cramér’s V and Association Measures</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Chi-square statistic: 17.352 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>N: 200 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>min(r-1, c-1): 1 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Cramér's V: 0.2946 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Interpretation: Medium effect (benchmark ~0.30 for this table size)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                    X^2 df   P(&gt; X^2)
Likelihood Ratio 17.694  2 0.00014384
Pearson          17.352  2 0.00017064

Phi-Coefficient   : NA 
Contingency Coeff.: 0.283 
Cramer's V        : 0.295 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter04_test_of_independence_files/figure-html/cramers-heatmap-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Code explanation:</strong></p>
<ul>
<li>Cramér’s V is computed manually here to show the formula clearly; <code>vcd::assocstats()</code> computes it (and phi, contingency coefficient) in one call.</li>
<li>The heatmap of standardized residuals is more informative than a standard mosaic plot for larger tables — color immediately draws the eye to cells with the strongest departures from independence.</li>
<li><code>scale_fill_gradient2()</code> creates a diverging color scale centered at zero, perfect for signed residuals.</li>
</ul>
</section>
<section id="exercises-3" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="exercises-3"><span class="header-section-number">10.5</span> Exercises</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise 4.5
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the <code>HairEyeColor</code> chi-square result from Exercise 4.2:</p>
<ol type="a">
<li>Compute Cramér’s V manually from the <span class="math inline">\(\chi^2\)</span> statistic.</li>
<li>Use <code>vcd::assocstats()</code> to verify.</li>
<li>Interpret the effect size using the appropriate benchmark for the table dimensions.</li>
<li>Produce a standardized residuals heatmap and describe which hair-eye combinations drive the association.</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
<section id="correlation-tests" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Correlation Tests</h1>
<section id="introduction-5" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="introduction-5"><span class="header-section-number">11.1</span> Introduction</h2>
<p>When both variables are continuous (or at least ordinal with many levels), <strong>correlation</strong> quantifies the strength and direction of their linear relationship. But a sample correlation <span class="math inline">\(r\)</span> could arise by chance even when the true population correlation <span class="math inline">\(\rho = 0\)</span>. A <strong>correlation test</strong> determines whether the observed correlation is statistically distinguishable from zero. In this section we cover the two most important correlation measures: <strong>Pearson’s <span class="math inline">\(r\)</span></strong> for linear relationships between normally distributed variables, and <strong>Spearman’s <span class="math inline">\(\rho\)</span></strong> for monotone relationships with no normality requirement.</p>
</section>
<section id="theory-4" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="theory-4"><span class="header-section-number">11.2</span> Theory</h2>
<section id="pearson-correlation-test" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="pearson-correlation-test"><span class="header-section-number">11.2.1</span> Pearson Correlation Test</h3>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0: \rho = 0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \rho \neq 0\)</span> (or one-sided)</p>
<p>Given sample correlation <span class="math inline">\(r\)</span> from <span class="math inline">\(n\)</span> pairs, the test statistic is:</p>
<p><span class="math display">\[t = \frac{r\sqrt{n-2}}{\sqrt{1-r^2}} \sim t(n-2) \text{ under } H_0\]</span></p>
<p><strong>Assumptions:</strong></p>
<ol type="1">
<li>Both variables are continuous.</li>
<li>The relationship is <strong>linear</strong>.</li>
<li>Both variables are approximately <strong>normally distributed</strong> (bivariate normality).</li>
<li>Observations are independent.</li>
<li>No extreme outliers (Pearson’s <span class="math inline">\(r\)</span> is sensitive to outliers).</li>
</ol>
<p><strong>Confidence interval for <span class="math inline">\(\rho\)</span>:</strong> Use Fisher’s z-transformation: <span class="math display">\[z = \frac{1}{2}\ln\!\left(\frac{1+r}{1-r}\right), \quad \text{SE}(z) = \frac{1}{\sqrt{n-3}}\]</span></p>
<p>Then transform back to the correlation scale.</p>
</section>
<section id="spearman-rank-correlation-test" class="level3" data-number="11.2.2">
<h3 data-number="11.2.2" class="anchored" data-anchor-id="spearman-rank-correlation-test"><span class="header-section-number">11.2.2</span> Spearman Rank Correlation Test</h3>
<p><strong>Spearman’s <span class="math inline">\(\rho\)</span></strong> replaces raw values with <strong>ranks</strong> and computes Pearson’s <span class="math inline">\(r\)</span> on the ranks. This makes it robust to:</p>
<ul>
<li>Non-normality</li>
<li>Outliers</li>
<li>Monotone but non-linear relationships</li>
<li>Ordinal variables</li>
</ul>
<p><span class="math display">\[\rho_s = 1 - \frac{6\sum d_i^2}{n(n^2-1)}\]</span></p>
<p>where <span class="math inline">\(d_i\)</span> is the difference in ranks for pair <span class="math inline">\(i\)</span>. For large samples, a t-approximation is used for hypothesis testing.</p>
</section>
<section id="interpreting-correlation" class="level3" data-number="11.2.3">
<h3 data-number="11.2.3" class="anchored" data-anchor-id="interpreting-correlation"><span class="header-section-number">11.2.3</span> Interpreting Correlation</h3>
<table class="table-striped caption-top table">
<caption>Correlation strength benchmarks</caption>
<thead>
<tr class="header">
<th><span class="math inline">\(|r|\)</span> or <span class="math inline">\(|\rho|\)</span></th>
<th>Strength</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.00 – 0.19</td>
<td>Negligible</td>
</tr>
<tr class="even">
<td>0.20 – 0.39</td>
<td>Weak</td>
</tr>
<tr class="odd">
<td>0.40 – 0.59</td>
<td>Moderate</td>
</tr>
<tr class="even">
<td>0.60 – 0.79</td>
<td>Strong</td>
</tr>
<tr class="odd">
<td>0.80 – 1.00</td>
<td>Very strong</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Critical Reminder: Correlation ≠ Causation
</div>
</div>
<div class="callout-body-container callout-body">
<p>A significant correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> does not imply that <span class="math inline">\(X\)</span> causes <span class="math inline">\(Y\)</span>, nor that <span class="math inline">\(Y\)</span> causes <span class="math inline">\(X\)</span>. Both could be driven by a third variable <span class="math inline">\(Z\)</span> (confounding), or the association could be spurious. Always consider alternative explanations and visualize the scatterplot alongside the correlation coefficient.</p>
</div>
</div>
</section>
</section>
<section id="example-pearson-and-spearman-correlation-tests" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="example-pearson-and-spearman-correlation-tests"><span class="header-section-number">11.3</span> Example: Pearson and Spearman Correlation Tests</h2>
<p><strong>Example 4.5.</strong> A researcher examines the relationship between hours of sleep per night (<span class="math inline">\(X\)</span>) and cognitive performance score (<span class="math inline">\(Y\)</span>) in 40 participants.</p>
<p>Results: <span class="math inline">\(r = 0.61\)</span>, <span class="math inline">\(t_{38} = 4.73\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>, 95% CI: <span class="math inline">\((0.37, 0.78)\)</span>.</p>
<p><strong>Interpretation:</strong> There is a statistically significant, strong positive linear correlation between sleep duration and cognitive performance (<span class="math inline">\(r = 0.61\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). The 95% CI <span class="math inline">\((0.37, 0.78)\)</span> excludes zero, confirming the association. However, this is an observational study — we cannot conclude that more sleep <strong>causes</strong> better performance.</p>
</section>
<section id="r-example-pearson-and-spearman-correlation-tests" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="r-example-pearson-and-spearman-correlation-tests"><span class="header-section-number">11.4</span> R Example: Pearson and Spearman Correlation Tests</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Correlation Test Results: Horsepower vs. MPG</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Method</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">r / ρ</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t / S</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">95% CI Lower</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">cor</td>
<td style="text-align: left;">Pearson</td>
<td style="text-align: right;">-0.7762</td>
<td style="text-align: right;">-6.742</td>
<td style="text-align: left;">30</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">-0.885</td>
<td style="text-align: left;">-0.586</td>
</tr>
<tr class="even">
<td style="text-align: left;">rho</td>
<td style="text-align: left;">Spearman</td>
<td style="text-align: right;">-0.8947</td>
<td style="text-align: right;">10337.290</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter04_test_of_independence_files/figure-html/correlation-plot-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Code explanation:</strong></p>
<ul>
<li><code>cor.test(x, y, method, alternative)</code> tests both Pearson (<code>"pearson"</code>) and Spearman (<code>"spearman"</code>) correlations. Pearson returns a CI; Spearman does not (due to the rank-based nature).</li>
<li><code>exact = FALSE</code> in Spearman uses a normal approximation — necessary when ties are present in the data.</li>
<li><code>ggcorrplot()</code> produces a publication-ready correlation matrix. <code>type = "upper"</code> shows only the upper triangle to avoid redundancy.</li>
</ul>
</section>
<section id="exercises-4" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="exercises-4"><span class="header-section-number">11.5</span> Exercises</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise 4.6
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the <code>iris</code> dataset, test the correlation between <code>Sepal.Length</code> and <code>Petal.Length</code>.</p>
<ol type="a">
<li>Produce a scatterplot. Does the relationship appear linear?</li>
<li>Check normality of both variables (Shapiro-Wilk). Which correlation method is more appropriate?</li>
<li>Run both Pearson and Spearman tests. Compare and explain any differences.</li>
<li>Compute the full 4×4 correlation matrix for all numeric variables and visualize with <code>ggcorrplot()</code>.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise 4.7
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>anscombe</code> dataset contains four pairs of variables with nearly identical correlations but very different scatterplot shapes.</p>
<ol type="a">
<li>Compute Pearson’s <span class="math inline">\(r\)</span> for all four pairs (x1/y1, x2/y2, x3/y3, x4/y4).</li>
<li>Plot all four scatterplots in a 2×2 grid.</li>
<li>For which pairs is Pearson’s <span class="math inline">\(r\)</span> a misleading summary? What would be more appropriate?</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
<section id="point-biserial-and-phi-coefficients" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Point-Biserial and Phi Coefficients</h1>
<section id="introduction-6" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="introduction-6"><span class="header-section-number">12.1</span> Introduction</h2>
<p>Not all association problems involve two continuous or two categorical variables. In data science, binary variables are ubiquitous — pass/fail, churn/retain, click/no-click, disease/healthy. When one or both variables in a pair are binary, specialized correlation measures maintain interpretability while remaining mathematically consistent with the general correlation framework. The <strong>point-biserial correlation</strong> handles the binary-continuous case; the <strong>phi coefficient</strong> handles the binary-binary case.</p>
</section>
<section id="theory-5" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="theory-5"><span class="header-section-number">12.2</span> Theory</h2>
<section id="point-biserial-correlation-r_pb" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="point-biserial-correlation-r_pb"><span class="header-section-number">12.2.1</span> Point-Biserial Correlation (<span class="math inline">\(r_{pb}\)</span>)</h3>
<p>The <strong>point-biserial correlation</strong> measures the association between a <strong>naturally binary variable</strong> (coded 0/1) and a <strong>continuous variable</strong>. It is mathematically equivalent to Pearson’s <span class="math inline">\(r\)</span> computed between the 0/1 binary variable and the continuous variable:</p>
<p><span class="math display">\[r_{pb} = \frac{\bar{Y}_1 - \bar{Y}_0}{s_Y}\sqrt{\frac{n_1 n_0}{n^2}}\]</span></p>
<p>where <span class="math inline">\(\bar{Y}_1\)</span> and <span class="math inline">\(\bar{Y}_0\)</span> are the means of the continuous variable in the two groups, <span class="math inline">\(s_Y\)</span> is the overall standard deviation, and <span class="math inline">\(n_1\)</span>, <span class="math inline">\(n_0\)</span> are the group sizes.</p>
<p><strong>Significance testing:</strong> Because <span class="math inline">\(r_{pb}\)</span> is algebraically equivalent to Pearson’s <span class="math inline">\(r\)</span>, the same t-test applies:</p>
<p><span class="math display">\[t = \frac{r_{pb}\sqrt{n-2}}{\sqrt{1-r_{pb}^2}} \sim t(n-2)\]</span></p>
<p>This is equivalent to running an <strong>independent samples t-test</strong> comparing the two groups — the same information, expressed differently.</p>
<p><strong>Assumptions:</strong> The continuous variable should be approximately normally distributed within each group (same as the independent samples t-test).</p>
</section>
<section id="phi-coefficient-phi" class="level3" data-number="12.2.2">
<h3 data-number="12.2.2" class="anchored" data-anchor-id="phi-coefficient-phi"><span class="header-section-number">12.2.2</span> Phi Coefficient (<span class="math inline">\(\phi\)</span>)</h3>
<p>The <strong>phi coefficient</strong> measures association between <strong>two binary variables</strong>. It is Pearson’s <span class="math inline">\(r\)</span> applied to two 0/1 variables:</p>
<p><span class="math display">\[\phi = \frac{ad - bc}{\sqrt{(a+b)(c+d)(a+c)(b+d)}}\]</span></p>
<p>where <span class="math inline">\(a, b, c, d\)</span> are the four cells of a 2×2 contingency table. <span class="math inline">\(\phi\)</span> ranges from <span class="math inline">\(-1\)</span> to <span class="math inline">\(+1\)</span> and equals Cramér’s V for 2×2 tables.</p>
<p><strong>Interpretation benchmarks</strong> (same as Pearson’s <span class="math inline">\(r\)</span>):</p>
<ul>
<li><span class="math inline">\(|\phi| &lt; 0.10\)</span>: Negligible</li>
<li><span class="math inline">\(0.10 \leq |\phi| &lt; 0.30\)</span>: Weak</li>
<li><span class="math inline">\(0.30 \leq |\phi| &lt; 0.50\)</span>: Moderate</li>
<li><span class="math inline">\(|\phi| \geq 0.50\)</span>: Strong</li>
</ul>
</section>
<section id="biserial-vs.-point-biserial" class="level3" data-number="12.2.3">
<h3 data-number="12.2.3" class="anchored" data-anchor-id="biserial-vs.-point-biserial"><span class="header-section-number">12.2.3</span> Biserial vs.&nbsp;Point-Biserial</h3>
<p>A subtle distinction: the <strong>point-biserial</strong> is used when the binary variable is <em>truly</em> dichotomous (e.g., sex, treatment assignment). The <strong>biserial correlation</strong> is used when the binary variable is an artificially dichotomized continuous variable (e.g., pass/fail from a continuous score). The biserial correlation is larger in magnitude and corrects for the information lost by dichotomization.</p>
</section>
</section>
<section id="example-point-biserial-correlation" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="example-point-biserial-correlation"><span class="header-section-number">12.3</span> Example: Point-Biserial Correlation</h2>
<p><strong>Example 4.6.</strong> A study records whether students passed a preparatory course (0 = No, 1 = Yes) and their final exam score. Results: <span class="math inline">\(r_{pb} = 0.48\)</span>, <span class="math inline">\(t_{58} = 4.19\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>.</p>
<p><strong>Interpretation:</strong> Students who passed the preparatory course scored significantly higher on the final exam (<span class="math inline">\(r_{pb} = 0.48\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). This is a moderate-to-strong effect, indicating the preparatory course is associated with better exam performance. Note that this is equivalent to a two-sample t-test comparing exam scores between the two groups.</p>
</section>
<section id="r-example-point-biserial-and-phi-coefficients" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="r-example-point-biserial-and-phi-coefficients"><span class="header-section-number">12.4</span> R Example: Point-Biserial and Phi Coefficients</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>=== Point-Biserial Correlation ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>r_pb: 0.5998 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>t:    4.106 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>df:   30 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>p:    3e-04 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>95% CI: [ 0.318 , 0.784 ]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Equivalent Welch's t-test p-value: 0.0014 (same conclusion)</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>=== Phi Coefficient ===</code></pre>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Transmission × Efficiency (2×2 Table)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">High</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Auto</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manual</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sum</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">32</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Phi coefficient: 0.522 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Chi-square p-value: 0.0031 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Interpretation: Moderate-to-strong association</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter04_test_of_independence_files/figure-html/pb-plot-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Code explanation:</strong></p>
<ul>
<li><code>cor.test(binary, continuous, method = "pearson")</code> correctly computes the point-biserial correlation — no special function is needed since it is mathematically Pearson’s <span class="math inline">\(r\)</span>.</li>
<li>Phi is computed as <span class="math inline">\(\sqrt{\chi^2/N}\)</span> — identical to Cramér’s V for 2×2 tables.</li>
<li>The equivalence between point-biserial and the independent samples t-test is shown explicitly — both tests use the same information and yield the same p-value (up to the choice of equal/unequal variances).</li>
</ul>
</section>
<section id="exercises-5" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="exercises-5"><span class="header-section-number">12.5</span> Exercises</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise 4.8
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the <code>mtcars</code> dataset:</p>
<ol type="a">
<li>Compute the point-biserial correlation between <code>vs</code> (engine shape: 0 = V-shaped, 1 = straight) and <code>qsec</code> (quarter-mile time).</li>
<li>Verify this equals the Pearson correlation between the two variables.</li>
<li>Is there a significant association? Report in full.</li>
<li>Compute the phi coefficient between <code>vs</code> and <code>am</code> (both binary). What is the strength of this association?</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
<section id="partial-correlation" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> Partial Correlation</h1>
<section id="introduction-7" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="introduction-7"><span class="header-section-number">13.1</span> Introduction</h2>
<p>Simple bivariate correlation measures the relationship between two variables, but in real datasets variables are rarely isolated — many are influenced by common underlying factors. <strong>Partial correlation</strong> measures the association between two variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> <strong>after removing the influence of one or more control variables <span class="math inline">\(Z\)</span></strong>. It answers: <em>Is the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> real, or is it merely a reflection of both being related to <span class="math inline">\(Z\)</span>?</em> This is a crucial step in distinguishing genuine associations from spurious ones, and a natural bridge toward multiple regression (Chapter 10).</p>
</section>
<section id="theory-6" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="theory-6"><span class="header-section-number">13.2</span> Theory</h2>
<section id="first-order-partial-correlation" class="level3" data-number="13.2.1">
<h3 data-number="13.2.1" class="anchored" data-anchor-id="first-order-partial-correlation"><span class="header-section-number">13.2.1</span> First-Order Partial Correlation</h3>
<p>The <strong>first-order partial correlation</strong> between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> controlling for <span class="math inline">\(Z\)</span> is:</p>
<p><span class="math display">\[r_{XY \cdot Z} = \frac{r_{XY} - r_{XZ} \cdot r_{YZ}}{\sqrt{(1-r_{XZ}^2)(1-r_{YZ}^2)}}\]</span></p>
<p>where <span class="math inline">\(r_{XY}\)</span>, <span class="math inline">\(r_{XZ}\)</span>, <span class="math inline">\(r_{YZ}\)</span> are the zero-order (simple) Pearson correlations.</p>
<p><strong>Interpretation:</strong> <span class="math inline">\(r_{XY \cdot Z}\)</span> is the correlation between the <strong>residuals</strong> of regressing <span class="math inline">\(X\)</span> on <span class="math inline">\(Z\)</span> and the <strong>residuals</strong> of regressing <span class="math inline">\(Y\)</span> on <span class="math inline">\(Z\)</span> — it is the “pure” relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> once the linear effect of <span class="math inline">\(Z\)</span> is removed from both.</p>
</section>
<section id="significance-testing" class="level3" data-number="13.2.2">
<h3 data-number="13.2.2" class="anchored" data-anchor-id="significance-testing"><span class="header-section-number">13.2.2</span> Significance Testing</h3>
<p>The partial correlation is tested using a t-distribution with <span class="math inline">\(n - 2 - k\)</span> degrees of freedom, where <span class="math inline">\(k\)</span> is the number of control variables:</p>
<p><span class="math display">\[t = \frac{r_{XY \cdot Z}\sqrt{n-2-k}}{\sqrt{1-r_{XY \cdot Z}^2}} \sim t(n-2-k)\]</span></p>
</section>
<section id="partial-vs.-semi-partial-correlation" class="level3" data-number="13.2.3">
<h3 data-number="13.2.3" class="anchored" data-anchor-id="partial-vs.-semi-partial-correlation"><span class="header-section-number">13.2.3</span> Partial vs.&nbsp;Semi-Partial Correlation</h3>
<p>A related concept is the <strong>semi-partial (part) correlation</strong> <span class="math inline">\(r_{X(Y \cdot Z)}\)</span>: the correlation between <span class="math inline">\(X\)</span> and the part of <span class="math inline">\(Y\)</span> that is <strong>unique</strong> (not shared with <span class="math inline">\(Z\)</span>). It measures the unique contribution of <span class="math inline">\(Y\)</span> to <span class="math inline">\(X\)</span>, which is central to multiple regression (it is the square root of the <span class="math inline">\(\Delta R^2\)</span> when <span class="math inline">\(Y\)</span> is added to a regression already containing <span class="math inline">\(Z\)</span>).</p>
</section>
<section id="spurious-correlation" class="level3" data-number="13.2.4">
<h3 data-number="13.2.4" class="anchored" data-anchor-id="spurious-correlation"><span class="header-section-number">13.2.4</span> Spurious Correlation</h3>
<p>A <strong>spurious correlation</strong> occurs when <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are correlated only because both are caused by a third variable <span class="math inline">\(Z\)</span>. After partialling out <span class="math inline">\(Z\)</span>, the partial correlation drops to (near) zero. Classic example: ice cream sales and drowning rates are positively correlated — both are caused by hot weather (the confounder). The partial correlation controlling for temperature would be near zero.</p>
</section>
</section>
<section id="example-partial-correlation" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="example-partial-correlation"><span class="header-section-number">13.3</span> Example: Partial Correlation</h2>
<p><strong>Example 4.7.</strong> In the <code>mtcars</code> dataset, <code>mpg</code> and <code>hp</code> are strongly negatively correlated (<span class="math inline">\(r = -0.78\)</span>). But both are also related to car weight (<code>wt</code>): heavier cars tend to have more horsepower and worse fuel economy. Is the <code>mpg</code>-<code>hp</code> correlation “real” or partly a reflection of their shared relationship with <code>wt</code>?</p>
<ul>
<li><span class="math inline">\(r_{\text{mpg,hp}} = -0.78\)</span></li>
<li><span class="math inline">\(r_{\text{mpg,wt}} = -0.87\)</span></li>
<li><span class="math inline">\(r_{\text{hp,wt}} = +0.66\)</span></li>
</ul>
<p><strong>Partial correlation controlling for <code>wt</code>:</strong></p>
<p><span class="math display">\[r_{\text{mpg,hp} \cdot \text{wt}} = \frac{-0.78 - (-0.87)(0.66)}{\sqrt{(1-0.87^2)(1-0.66^2)}} = \frac{-0.78 + 0.574}{\sqrt{0.243 \times 0.564}} = \frac{-0.206}{0.370} \approx -0.557\]</span></p>
<p>The partial correlation (<span class="math inline">\(-0.56\)</span>) is notably weaker than the zero-order correlation (<span class="math inline">\(-0.78\)</span>), suggesting that part of the <code>mpg</code>-<code>hp</code> relationship is mediated through vehicle weight. However, a meaningful negative relationship remains even after controlling for weight.</p>
</section>
<section id="r-example-partial-correlation" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="r-example-partial-correlation"><span class="header-section-number">13.4</span> R Example: Partial Correlation</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>=== Zero-Order Correlations ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        mpg     hp     wt   disp
mpg   1.000 -0.776 -0.868 -0.848
hp   -0.776  1.000  0.659  0.791
wt   -0.868  0.659  1.000  0.888
disp -0.848  0.791  0.888  1.000</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>=== Partial Correlation: mpg &amp; hp | wt ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Zero-order r(mpg, hp):      -0.7762 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Partial r(mpg, hp | wt):    -0.547 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>t-statistic:                -3.519 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>df:                         29 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>p-value:                    0.0015 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>=== Partial Correlation Matrix (all pairs, no controls) ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        mpg     hp   disp   qsec
mpg   1.000 -0.342 -0.568 -0.154
hp   -0.342  1.000  0.393 -0.668
disp -0.568  0.393  1.000  0.151
qsec -0.154 -0.668  0.151  1.000</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter04_test_of_independence_files/figure-html/partial-plot-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Code explanation:</strong></p>
<ul>
<li><code>pcor.test(x, y, z)</code> from <code>ppcor</code> computes the first-order partial correlation between <code>x</code> and <code>y</code> controlling for <code>z</code>, with a significance test.</li>
<li><code>pcor(data_frame)</code> computes the full partial correlation matrix (each pair controlled for all others) — analogous to <code>cor()</code> for zero-order correlations.</li>
<li>Panels A and B illustrate the concept geometrically: Panel B shows the scatterplot of <strong>residuals</strong> — the pure association between <code>mpg</code> and <code>hp</code> after both have been “de-weighted” by <code>wt</code>.</li>
</ul>
<p><strong>Try modifying:</strong> Control for both <code>wt</code> and <code>disp</code> simultaneously using <code>pcor.test(mpg, hp, cbind(wt, disp))</code>. Does the partial correlation weaken further?</p>
</section>
<section id="exercises-6" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="exercises-6"><span class="header-section-number">13.5</span> Exercises</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise 4.9
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the <code>iris</code> dataset, <code>Sepal.Length</code> and <code>Petal.Length</code> are strongly correlated (<span class="math inline">\(r \approx 0.87\)</span>). Species is a potential confounder.</p>
<ol type="a">
<li>Compute the zero-order Pearson correlation between <code>Sepal.Length</code> and <code>Petal.Length</code>.</li>
<li>Encode <code>Species</code> as a numeric variable (1, 2, 3) and compute the partial correlation controlling for it using <code>pcor.test()</code>.</li>
<li>Does the partial correlation differ substantially from the zero-order correlation? What does this suggest?</li>
<li>Visualize both zero-order and partial relationships as scatterplots (color points by species in panel A).</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise 4.10 (Challenge)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using <code>mtcars</code>, construct a full analysis comparing zero-order and partial correlations for the variable pair (<code>wt</code>, <code>mpg</code>), controlling for <code>cyl</code> (number of cylinders).</p>
<ol type="a">
<li>Compute zero-order <span class="math inline">\(r\)</span>(wt, mpg) and partial <span class="math inline">\(r\)</span>(wt, mpg | cyl).</li>
<li>Do the correlations differ? What does this tell us about the role of engine size?</li>
<li>Produce a 2-panel residual scatterplot similar to the chapter example.</li>
<li>Write a 150-word research summary reporting both correlations in APA format.</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
<section id="chapter-lab-activity-exploring-independence-with-the-titanic-and-mtcars-datasets" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> Chapter Lab Activity: Exploring Independence with the <code>titanic</code> and <code>mtcars</code> Datasets</h1>
<section id="objectives" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="objectives"><span class="header-section-number">14.1</span> Objectives</h2>
<p>In this lab you will apply the full spectrum of independence tests to real data — choosing the correct test based on variable types, checking assumptions, reporting effect sizes, and visualizing associations. You will work with the built-in <code>Titanic</code> dataset (categorical variables) and <code>mtcars</code> (mixed variable types).</p>
</section>
<section id="the-datasets" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="the-datasets"><span class="header-section-number">14.2</span> The Datasets</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Titanic Dataset (first 10 rows)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Class</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Sex</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Age</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Survived</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Total passengers: 2201 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Variables: Class Sex Age Survived </code></pre>
</div>
</div>
</section>
<section id="lab-task-1-survival-class-chi-square-test" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="lab-task-1-survival-class-chi-square-test"><span class="header-section-number">14.3</span> Lab Task 1: Survival × Class — Chi-Square Test</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Passenger Class × Survival Status</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Yes</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1st</td>
<td style="text-align: right;">122</td>
<td style="text-align: right;">203</td>
<td style="text-align: right;">325</td>
</tr>
<tr class="even">
<td style="text-align: left;">2nd</td>
<td style="text-align: right;">167</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">285</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3rd</td>
<td style="text-align: right;">528</td>
<td style="text-align: right;">178</td>
<td style="text-align: right;">706</td>
</tr>
<tr class="even">
<td style="text-align: left;">Crew</td>
<td style="text-align: right;">673</td>
<td style="text-align: right;">212</td>
<td style="text-align: right;">885</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sum</td>
<td style="text-align: right;">1490</td>
<td style="text-align: right;">711</td>
<td style="text-align: right;">2201</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Square Test Results:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>χ²( 3 ) = 190.4 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>p-value: 0 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>All expected ≥ 5: TRUE </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Cramér's V: 0.2941 </code></pre>
</div>
</div>
</section>
<section id="lab-task-2-survival-sex-fishers-exact-test" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="lab-task-2-survival-sex-fishers-exact-test"><span class="header-section-number">14.4</span> Lab Task 2: Survival × Sex — Fisher’s Exact Test</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Sex × Survival Status</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Yes</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Male</td>
<td style="text-align: right;">1364</td>
<td style="text-align: right;">367</td>
<td style="text-align: right;">1731</td>
</tr>
<tr class="even">
<td style="text-align: left;">Female</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">344</td>
<td style="text-align: right;">470</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sum</td>
<td style="text-align: right;">1490</td>
<td style="text-align: right;">711</td>
<td style="text-align: right;">2201</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Chi-Square: χ²(1) = 456.87 , p = 0 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Fisher's Exact: p = 0 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Odds Ratio: 10.132   95% CI: [ 7.977 , 12.929 ]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Phi coefficient: 0.4556 </code></pre>
</div>
</div>
</section>
<section id="lab-task-3-correlation-analysis-mtcars" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="lab-task-3-correlation-analysis-mtcars"><span class="header-section-number">14.5</span> Lab Task 3: Correlation Analysis — mtcars</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter04_test_of_independence_files/figure-html/lab-task3-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lab-task-4-partial-correlation-controlling-for-weight" class="level2" data-number="14.6">
<h2 data-number="14.6" class="anchored" data-anchor-id="lab-task-4-partial-correlation-controlling-for-weight"><span class="header-section-number">14.6</span> Lab Task 4: Partial Correlation — Controlling for Weight</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Zero-Order vs. Partial Correlations (controlling for wt)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable Pair</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Zero-Order r</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Partial r &amp;#124; wt</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Change in r</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mpg ~ hp</td>
<td style="text-align: right;">-0.7762</td>
<td style="text-align: right;">-0.5470</td>
<td style="text-align: right;">0.0015</td>
<td style="text-align: right; font-weight: bold; color: tomato !important;">0.2292</td>
</tr>
<tr class="even">
<td style="text-align: left;">mpg ~ disp</td>
<td style="text-align: right;">-0.8476</td>
<td style="text-align: right;">-0.3372</td>
<td style="text-align: right;">0.0636</td>
<td style="text-align: right; font-weight: bold; color: tomato !important;">0.5104</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hp ~ disp</td>
<td style="text-align: right;">0.7909</td>
<td style="text-align: right;">0.5954</td>
<td style="text-align: right;">0.0004</td>
<td style="text-align: right; font-weight: bold; color: tomato !important;">-0.1956</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="lab-task-5-comprehensive-visualization" class="level2" data-number="14.7">
<h2 data-number="14.7" class="anchored" data-anchor-id="lab-task-5-comprehensive-visualization"><span class="header-section-number">14.7</span> Lab Task 5: Comprehensive Visualization</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter04_test_of_independence_files/figure-html/lab-task5-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lab-discussion-questions" class="level2" data-number="14.8">
<h2 data-number="14.8" class="anchored" data-anchor-id="lab-discussion-questions"><span class="header-section-number">14.8</span> Lab Discussion Questions</h2>
<p>Answer the following in writing:</p>
<ol type="1">
<li><p><strong>Test Selection:</strong> In Lab Task 2, both chi-square and Fisher’s exact test give nearly identical p-values. Why? Does the very large sample size (<span class="math inline">\(N = 2201\)</span>) affect which test is preferable?</p></li>
<li><p><strong>Effect Size vs.&nbsp;Significance:</strong> The chi-square test for Class × Survival is highly significant (<span class="math inline">\(p &lt; 0.001\)</span>). Interpret Cramér’s V = 0.294. Is this a practically important association? How would you communicate this to a non-statistician?</p></li>
<li><p><strong>Odds Ratio Interpretation:</strong> Fisher’s test for Sex × Survival gives an odds ratio. Interpret this in plain language: what does the odds ratio tell us about the relationship between being female and surviving?</p></li>
<li><p><strong>Partial Correlation:</strong> After controlling for weight (<code>wt</code>), the correlation between <code>mpg</code> and <code>hp</code> weakens. Does this mean weight fully “explains” the mpg-hp relationship? What other variables might also act as confounders?</p></li>
<li><p><strong>Spurious Correlation:</strong> Can you identify a potential spurious correlation in the <code>mtcars</code> dataset? Propose which third variable might be the confounder and describe how you would test this using partial correlation.</p></li>
</ol>
<hr>
</section>
</section>
<section id="chapter-summary" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> Chapter Summary</h1>
<section id="summary" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">15.1</span> Summary</h2>
<p>This chapter built a comprehensive toolkit for testing independence and measuring association across all combinations of variable types:</p>
<ul>
<li><strong>The concept of independence</strong> — two variables are independent if knowing one provides no information about the other; this must be tested formally, not assumed.</li>
<li><strong>Chi-square test</strong> — the standard test for two categorical variables; based on comparing observed to expected frequencies in a contingency table.</li>
<li><strong>Fisher’s Exact Test</strong> — the correct alternative when expected cell frequencies are small; computes exact probabilities rather than relying on asymptotic approximations.</li>
<li><strong>Cramér’s V</strong> — standardizes chi-square to a 0–1 scale, enabling interpretation of association strength independently of sample size and table dimensions.</li>
<li><strong>Pearson and Spearman correlation tests</strong> — test whether linear (Pearson) or monotone (Spearman) relationships between continuous or ordinal variables are significantly different from zero.</li>
<li><strong>Point-biserial and phi coefficients</strong> — extend the correlation framework to binary variables, maintaining mathematical consistency with Pearson’s <span class="math inline">\(r\)</span>.</li>
<li><strong>Partial correlation</strong> — isolates the “pure” relationship between two variables after removing the influence of one or more control variables, helping distinguish real associations from spurious ones.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Key Formulas to Know
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Chi-Square Statistic:</strong> <span class="math display">\[\chi^2 = \sum_{i,j} \frac{(O_{ij} - E_{ij})^2}{E_{ij}}, \quad E_{ij} = \frac{R_i C_j}{N}\]</span></p>
<p><strong>Cramér’s V:</strong> <span class="math display">\[V = \sqrt{\frac{\chi^2/N}{\min(r-1,\, c-1)}}\]</span></p>
<p><strong>Pearson Correlation t-test:</strong> <span class="math display">\[t = \frac{r\sqrt{n-2}}{\sqrt{1-r^2}} \sim t(n-2)\]</span></p>
<p><strong>First-Order Partial Correlation:</strong> <span class="math display">\[r_{XY \cdot Z} = \frac{r_{XY} - r_{XZ} \cdot r_{YZ}}{\sqrt{(1-r_{XZ}^2)(1-r_{YZ}^2)}}\]</span></p>
<p><strong>Phi Coefficient (2×2):</strong> <span class="math display">\[\phi = \frac{ad - bc}{\sqrt{(a+b)(c+d)(a+c)(b+d)}}\]</span></p>
</div>
</div>
</section>
<section id="references" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="references"><span class="header-section-number">15.2</span> References</h2>
<p>Anderson, E. (1935). The irises of the Gaspé Peninsula. <em>Bulletin of the American Iris Society</em>, <em>59</em>, 2–5.</p>
<p>Cohen, J. (1988). <em>Statistical power analysis for the behavioral sciences</em> (2nd ed.). Lawrence Erlbaum Associates.</p>
<p>Fox, J., &amp; Weisberg, S. (2019). <em>An R companion to applied regression</em> (3rd ed.). SAGE.</p>
<p>Henderson, H. V., &amp; Velleman, P. F. (1981). Building multiple regression models interactively. <em>Biometrics</em>, <em>37</em>(2), 391–411.</p>
<p>Kassambara, A. (2023). <em>rstatix: Pipe-friendly framework for basic statistical tests</em> (R package version 0.7.2). https://CRAN.R-project.org/package=rstatix</p>
<p>Kim Larsen. (2015). <em>ppcor: An R package for a fast calculation to semi-partial correlation coefficients</em> (R package version 1.1). https://CRAN.R-project.org/package=ppcor</p>
<p>Meyer, D., Zeileis, A., &amp; Hornik, K. (2023). <em>vcd: Visualizing categorical data</em> (R package version 1.4-11). https://CRAN.R-project.org/package=vcd</p>
<p>Pedersen, T. L. (2022). <em>patchwork: The composer of plots</em> (R package version 1.1.2). https://CRAN.R-project.org/package=patchwork</p>
<p>R Core Team. (2024). <em>R: A language and environment for statistical computing</em>. R Foundation for Statistical Computing. https://www.R-project.org/</p>
<p>Shapiro, S. S., &amp; Wilk, M. B. (1965). An analysis of variance test for normality. <em>Biometrika</em>, <em>52</em>(3/4), 591–611.</p>
<p>Sievert, C., &amp; others. (2023). <em>ggcorrplot: Visualization of a correlation matrix using ggplot2</em> (R package version 0.1.4). https://CRAN.R-project.org/package=ggcorrplot</p>
<p>Spearman, C. (1904). “General intelligence,” objectively determined and measured. <em>American Journal of Psychology</em>, <em>15</em>(2), 201–292.</p>
<p>Wei, T., &amp; Simko, V. (2021). <em>corrplot: Visualization of a correlation matrix</em> (R package version 0.92). https://CRAN.R-project.org/package=corrplot</p>
<p>Wickham, H. (2016). <em>ggplot2: Elegant graphics for data analysis</em>. Springer.</p>
<p>Wickham, H., Averick, M., Bryan, J., Chang, W., McGowan, L. D., François, R., Grolemund, G., Hayes, A., Henry, L., Hester, J., Kuhn, M., Pedersen, T. L., Miller, E., Bache, S. M., Müller, K., Ooms, J., Robinson, D., Seidel, D. P., Spinu, V., … Yutani, H. (2019). Welcome to the tidyverse. <em>Journal of Open Source Software</em>, <em>4</em>(43), 1686.</p>
<p>Xie, Y. (2015). <em>Dynamic documents with R and knitr</em> (2nd ed.). CRC Press.</p>
<hr>
<p><em>End of Chapter 4. Proceed to Chapter 5: Data Sampling Techniques.</em></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter03_hypothesis_testing.html" class="pagination-link" aria-label="Chapter 3: Hypothesis Testing">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 3: Hypothesis Testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter05_data_sampling.html" class="pagination-link" aria-label="Chapter 5: Data Sampling Techniques">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 5: Data Sampling Techniques</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>